"use strict";
var express = require('express');
var router = express.Router();
var authController = require('../controllers/auth.controller');
var userController = require('../controllers/user.controller');
router.get('/get/:id', userController.getUser);
router.post('/sign-up', authController.signUp);
router.post('/login', authController.login);
router.get('/logout', authController.logout);
module.exports = router;
